 #!/bin/tcsh
echo Processing RelValMinBias_AOD.size ...
../printMainSizes.sh RelValMinBias_AOD.size > RelValMinBias_AOD_MainSizes.txt
echo Processing RelValTTbar_AOD.size ...
../printMainSizes.sh RelValTTbar_AOD.size >  RelValTTbar_AOD_MainSizes.txt
echo Processing RelValTTbar_PU25ns_AOD.size ...
../printMainSizes.sh RelValTTbar_PU25ns_AOD.size > RelValTTbar_PU25ns_AOD_MainSizes.txt
echo Processing RelValTTbar_PU50ns_AOD.size ...
../printMainSizes.sh RelValTTbar_PU50ns_AOD.size > RelValTTbar_PU50ns_AOD_MainSizes.txt
echo Processing RelValZMM_AOD.size ...
../printMainSizes.sh RelValZMM_AOD.size > RelValZMM_AOD_MainSizes.txt
echo Processing RelValZMM_PU25ns_AOD.size ...
../printMainSizes.sh RelValZMM_PU25ns_AOD.size > RelValZMM_PU25ns_AOD_MainSizes.txt
echo Processing RelValZMM_PU50ns_AOD.size ...
../printMainSizes.sh RelValZMM_PU50ns_AOD.size > RelValZMM_PU50ns_AOD_MainSizes.txt
echo done
