 #!/bin/tcsh
echo Processing RelValTTbar_PU25ns_MINIAOD.size ...
../printMINIAODSizes.sh patBranchesSelection.txt RelValTTbar_PU25ns_MINIAOD.size > RelValTTbar_PU25ns_AOD_MINIAODsizes.txt
echo Processing RelValTTbar_PU50ns_MINIAOD.size ...
../printMINIAODSizes.sh patBranchesSelection.txt RelValTTbar_PU50ns_MINIAOD.size > RelValTTbar_PU50ns_AOD_MINIAODsizes.txt
echo Processing RelValZMM_PU25ns_MINIAOD.size ...
../printMINIAODSizes.sh patBranchesSelection.txt RelValZMM_PU25ns_MINIAOD.size > RelValZMM_PU25ns_AOD_MINIAODsizes.txt
echo Processing RelValZMM_PU50ns_MINIAOD.size ...
../printMINIAODSizes.sh patBranchesSelection.txt RelValZMM_PU50ns_MINIAOD.size > RelValZMM_PU50ns_AOD_MINIAODsizes.txt
echo done
