 #!/bin/tcsh
 echo Processing RelValMinBias_AOD.size ...
 ../printPFSizes.sh groups_pf.txt RelValMinBias_AOD.size > RelValMinBias_AOD_PFAODsizes.txt
 echo Processing RelValTTbar_AOD.size ...
 ../printPFSizes.sh groups_pf.txt RelValTTbar_AOD.size > RelValTTbar_AOD_PFAODsizes.txt
 echo Processing RelValTTbar_PU25ns_AOD.size ...
 ../printPFSizes.sh groups_pf.txt RelValTTbar_PU25ns_AOD.size > RelValTTbar_PU25ns_AOD_PFAODsizes.txt
 echo Processing RelValTTbar_PU50ns_AOD.size ...
 ../printPFSizes.sh groups_pf.txt RelValTTbar_PU50ns_AOD.size > RelValTTbar_PU50ns_AOD_PFAODsizes.txt
 echo Processing RelValZMM_AOD.size ...
 ../printPFSizes.sh groups_pf.txt RelValZMM_AOD.size > RelValZMM_AOD_PFAODsizes.txt
 echo Processing RelValZMM_PU25ns_AOD.size ...
 ../printPFSizes.sh groups_pf.txt RelValZMM_PU25ns_AOD.size > RelValZMM_PU25ns_AOD_PFAODsizes.txt
 echo Processing RelValZMM_PU50ns_AOD.size ...
 ../printPFSizes.sh groups_pf.txt RelValZMM_PU50ns_AOD.size > RelValZMM_PU50ns_AOD_PFAODsizes.txt
 echo done

