 #!/bin/tcsh
 echo Processing RelValMinBias_RECO.size ...
 ../printPFSizes.sh pfBranchesSelection.txt RelValMinBias_RECO.size > RelValMinBias_RECO_PFRECOsizes.txt
 echo Processing RelValTTbar_RECO.size ...
 ../printPFSizes.sh pfBranchesSelection.txt RelValTTbar_RECO.size > RelValTTbar_RECO_PFRECOsizes.txt
 echo Processing RelValTTbar_PU25ns_RECO.size ...
 ../printPFSizes.sh pfBranchesSelection.txt RelValTTbar_PU25ns_RECO.size > RelValTTbar_PU25ns_RECO_PFRECOsizes.txt
 echo Processing RelValTTbar_PU50ns_RECO.size ...
 ../printPFSizes.sh pfBranchesSelection.txt RelValTTbar_PU50ns_RECO.size > RelValTTbar_PU50ns_RECO_PFRECOsizes.txt
 echo Processing RelValZMM_RECO.size ...
 ../printPFSizes.sh pfBranchesSelection.txt RelValZMM_RECO.size > RelValZMM_RECO_PFRECOsizes.txt
 echo Processing RelValZMM_PU25ns_RECO.size ...
 ../printPFSizes.sh pfBranchesSelection.txt RelValZMM_PU25ns_RECO.size > RelValZMM_PU25ns_RECO_PFRECOsizes.txt
 echo Processing RelValZMM_PU50ns_RECO.size ...
 ../printPFSizes.sh pfBranchesSelection.txt RelValZMM_PU50ns_RECO.size > RelValZMM_PU50ns_RECO_PFRECOsizes.txt
 echo done

