 #!/bin/tcsh
echo Processing RelValMinBias_RECO.size ...
../printMainSizes.sh RelValMinBias_RECO.size > RelValMinBias_RECO_MainSizes.txt
echo Processing RelValTTbar_RECO.size ...
../printMainSizes.sh RelValTTbar_RECO.size >  RelValTTbar_RECO_MainSizes.txt
echo Processing RelValTTbar_PU25ns_RECO.size ...
../printMainSizes.sh RelValTTbar_PU25ns_RECO.size > RelValTTbar_PU25ns_RECO_MainSizes.txt
echo Processing RelValTTbar_PU50ns_RECO.size ...
../printMainSizes.sh RelValTTbar_PU50ns_RECO.size > RelValTTbar_PU50ns_RECO_MainSizes.txt
echo Processing RelValZMM_RECO.size ...
../printMainSizes.sh RelValZMM_RECO.size > RelValZMM_RECO_MainSizes.txt
echo Processing RelValZMM_PU25ns_RECO.size ...
../printMainSizes.sh RelValZMM_PU25ns_RECO.size > RelValZMM_PU25ns_RECO_MainSizes.txt
echo Processing RelValZMM_PU50ns_RECO.size ...
../printMainSizes.sh RelValZMM_PU50ns_RECO.size > RelValZMM_PU50ns_RECO_MainSizes.txt
echo done
