 #!/bin/tcsh
echo Processing RelValMinBias_RECO.size ...
../printRECOSizes.sh recoBranchesSelection.txt RelValMinBias_RECO.size > RelValMinBias_RECO_RECOsizes.txt
echo Processing RelValTTbar_RECO.size ...
../printRECOSizes.sh recoBranchesSelection.txt RelValTTbar_RECO.size > RelValTTbar_RECO_RECOsizes.txt
echo Processing RelValTTbar_PU25ns_RECO.size ...
../printRECOSizes.sh recoBranchesSelection.txt RelValTTbar_PU25ns_RECO.size > RelValTTbar_PU25ns_RECO_RECOsizes.txt
echo Processing RelValTTbar_PU50ns_RECO.size ...
../printRECOSizes.sh recoBranchesSelection.txt RelValTTbar_PU50ns_RECO.size > RelValTTbar_PU50ns_RECO_RECOsizes.txt
echo Processing RelValZMM_RECO.size ...
../printRECOSizes.sh recoBranchesSelection.txt RelValZMM_RECO.size > RelValZMM_RECO_RECOsizes.txt
echo Processing RelValZMM_PU25ns_RECO.size ...
../printRECOSizes.sh recoBranchesSelection.txt RelValZMM_PU25ns_RECO.size > RelValZMM_PU25ns_RECO_RECOsizes.txt
echo Processing RelValZMM_PU50ns_RECO.size ...
../printRECOSizes.sh recoBranchesSelection.txt RelValZMM_PU50ns_RECO.size > RelValZMM_PU50ns_RECO_RECOsizes.txt
echo done
