 #!/bin/tcsh
echo Processing RelValTTbar_PU25ns_MINIAOD.size ...
../printMainSizes_MINIAOD.sh RelValTTbar_PU25ns_MINIAOD.size > RelValTTbar_PU25ns_MINIAOD_MainSizes.txt
echo Processing RelValTTbar_PU50ns_MINIAOD.size ...
../printMainSizes_MINIAOD.sh RelValTTbar_PU50ns_MINIAOD.size > RelValTTbar_PU50ns_MINIAOD_MainSizes.txt
echo Processing RelValZMM_PU25ns_MINIAOD.size ...
../printMainSizes_MINIAOD.sh RelValZMM_PU25ns_MINIAOD.size > RelValZMM_PU25ns_MINIAOD_MainSizes.txt
echo Processing RelValZMM_PU50ns_MINIAOD.size ...
../printMainSizes_MINIAOD.sh RelValZMM_PU50ns_MINIAOD.size > RelValZMM_PU50ns_MINIAOD_MainSizes.txt
echo done
